### ISSUE TITLE
[14.0][base_user_role_profile] Template and js script doesn't exists

### ISSUE THREAD

**Issue by robyf70** [OCA/server-backend#155]
This template doesn't exists 

https://github.com/OCA/server-backend/blob/597659b97147b61b87ec5f637fdda4c6e4446861/base_user_role_profile/__manifest__.py#L20

And also this js file
https://github.com/OCA/server-backend/blob/597659b97147b61b87ec5f637fdda4c6e4446861/base_user_role_profile/views/assets.xml#L11

**Comment by dipak-shah** [comment]
Kevin Khao <[kevin.khao@akretion.com](mailto:kevin.khao@akretion.com)>
Sébastien Beau <[sebastien.beau@akretion.com](mailto:sebastien.beau@akretion.com)>

@kevinkhao @sebastienbeau @alan196 @Guille @sebalix  Seems like this one is surely missed. any reason for that ? please reopen this as an issue because the JS file is still missing. and the powerful module is not functioning.
